export const SET_USER_INFO_ACTION = 'SET_USER_INFO_ACTION'
export const SET_OP_TASK_DTO_ACTION = 'SET_OP_TASK_DTO_ACTION'
export const SET_ROOM_ACTION = 'SET_ROOM_ACTION'
export const SET_TOKEN_ACTION = 'SET_TOKEN_ACTION'
