export const iconMaps: Map<string, string> = new Map<string, string>([
  ['1', 'icon-shoushupaitai'],
  ['2', 'icon-weikaishishoushu'],
  ['3', 'icon-hedui'],
  ['4', 'icon-shoushujieshu'],
  ['5', 'icon-zhuansongzhong'],
  ['6', 'icon-shoushushi1'],
  ['7', 'icon-shoushujian'],
  ['8', 'icon-mazui'],
  ['9', 'icon-shoushuzhong'],
  ['10', 'icon-suxing'],
  ['11', 'icon-jinfusushi'],
  ['12', 'icon-suxing'],
  ['13', 'icon-chufusushi'],
  ['14', 'icon-chufusushi'],
  ['15', 'icon-huibingfang'],
  ['16', 'icon-jieshu'],
])
