enum STATUS_TYPE {
  SUCCESS = '保存成功',
  ERROR = '保存失败',
  EDIT_SUCCESS = '修改成功',
  EDIT_ERROR = '修改失败',
  IMPORT_SUCCESS = '导入成功',
  IMPORT_ERROR = '导入失败',
  DELETE_SUCESS = '删除成功',
  DELETE_ERROR = '删除失败',
  RUN_SUCCESS = '执行一次请求成功，任务已进入待执行队列',
  RUN_ERROR = '执行失败',
  UPLOAD_ERROR = '上传失败',
  CONFIRM_ERROR = '数据确认失败',
  REPORT_SUCCESS = '上报请求成功，任务已进入待执行队列',
  REPORT_ERROR = '上报失败',
  COMMIT_SUCCESS = '提交成功',
  COMMIT_ERROR = '提交失败',
  MAP_SUCCESS = '映射成功',
  MAP_ERROR = '映射失败',
  FIRE_MAP_SUCCESS = '解除映射成功',
  FIRE_MAP_ERROR = '解除映射失败',
  SELECT_ORIGIN = '请选择源字典',
  SELECT_STANDARD = '请选择标准字典',
  STOP_SUCCESS = '终止成功',
  STOP_ERROR = '终止失败',
}

enum MESSAGE_TYPE {
  DELETE_TITLE = '确认删除',
  DELETE_MSG = '删除后数据将无法恢复，请谨慎操作',
  STOP_TASK_TITLE = '终止任务',
  STOP_TASK_MSG = '任务正在运行，确定终止？',
  CONFIRM = '确认',
  CANCEL = '取消',
  OUT = '退出',
  CONFIRM_STOP_TITLE = '确认停止',
  CONFIRM_DISABLED_TITLE = '确认禁用',
  CONFIRM_STOP_MSG = '停止后，接口任务将不再执行，请谨慎操作',
  CONFIRM_DISABLED_MSG = '禁用后，接口任务将不再执行，请谨慎操作',
  CONFORM_START_TITLE = '确认启动',
  CONFORM_ABLED_TITLE = '确认启用',
  CONFIRM_START_MSG = '启动后，接口任务将按计划执行',
  CONFIRM_ABLED_MSG = '启用后，接口任务将按计划执行',
  CONFIRM_RUN_TITLE = '确认执行',
  CONFIRM_RUN_MSG = '确认立即执行调度',
  CONFIRM_MAP_TITLE = '提交映射',
  CONFIRM_MAP_MSG = '确认提交映射？提交后映射关系将用于抽取数据的校验及转换',
  UNMAP_TITLE = '解除映射',
  UNMAP_MSG = '确认解除映射？',
  IMPORT_MSG = '确认上报？',
  IMPORT_TITLE = '确认上报',
  CONFIRM_SUBJECT_TITLE = '提示',
  CONFIRM_SUBJECT_MSG = '确认提交?',
}

enum CHECK_STATUS {
  SUCCESS = '上报成功',
  SUCCESS_ONLY = '成功',
  ERROR = '失败',
  ERROR_TIMEOUT = '失败（超时）',
  SELF_FAIL = '自检失败',
  FAIL = '上报失败',
  RETRY_FAIL = '重传失败',
  WAIT_REPORT = '待上报',
  REPORTING = '上报中',
  EXTRACT_FAIL = '重抽失败',
  NOT_TRIGGER = '未调度',
}

export { STATUS_TYPE, MESSAGE_TYPE, CHECK_STATUS };
